### ISSUE TITLE
This repo exposes paid plugin to public.

### ISSUE THREAD

**Issue by KyryloKuzyk** [ar-exhibition/app#1]
Hi!

This is Kirill, creator of the plugin:
https://assetstore.unity.com/packages/tools/utilities/ar-foundation-editor-remote-168773

Please make your repository private (or remove it) because it exposes the plugin's source code to the public. To be exact, the 'Assets/Plugins/Installer' folder

Adding the folder to ignore will not help because the plugin will remain visible in the history of commits.

Thanks for your understanding :)

**Comment by marlon360** [comment]
Hi Kirill,

we are so sorry for this mistake.
We cleaned the git history and the files shouldn't be public anymore.

Please reopen this issue, if there are still any problems!

And thank you very much for this awesome plugin. It saves us so much time!

**Comment by KyryloKuzyk** [comment]
Thanks!
I'm glad the plugin is useful for you :)
